library(TCGAbiolinks)
library(maftools)
paad.maf <- GDCquery_Maf("PAAD", pipelines = "mutect2")
paad <- read.maf(maf=luad.maf)
paad
getSampleSummary(paad)
getGeneSummary(paad)
plotmafSummary(maf = paad, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
oncoplot(maf = paad, top = 10, fontSize = 12)
oncostrip(maf = paad, genes = c('KRAS','EGFR'))
